### ISSUE TITLE
STT0025: split audio and uploading script for stt_nw (news)

### ISSUE THREAD

**Issue by gangagyatso4364** [OpenPecha/stt-split-audio#1]
### Description
create spilt audio folder for stt_nw. use the script stt_hs scripts for reference.
stt_hs: [https://github.com/OpenPecha/stt-split-audio](url)
### Completion Criteria
The stt_nw data are shown in stt.pecha.tools stats .
---
### Subtasks
- [x] download the downloading from youtube link script and make csv script from stt_hs
- [x] adjust the variable names such as sheet id, column name, group name and so on to be consistent with stt_nw
- [x] download audio, spilt audio, then run inference, create csv and upload to database.

**Comment by gangagyatso4364** [comment]
update stt split audio repo
