### ISSUE TITLE
STT0045: Create a script to Upload stt history data and delete after saving the stt_hs in transcribing state from stt pecha tools.

### ISSUE THREAD

**Issue by gangagyatso4364** [OpenPecha/stt-split-audio#16]
### Description
the current history data in stt pecha tools are mostly thrown in trash so we need to upload better history data for more productivity.

### Completion Criteria
new history data uploaded in stt pecha tools.
### Subtask
- [x] save the current history data in state transcribing.
- [x] delete the stt_hs from stt pecha tools database after saving in aws
- [x] create a script upload new history data.
- [x] upload stt hs in stt pecha tools.
