### ISSUE TITLE
STT0027: script to adjust the existence of shed in transcript inference.

### ISSUE THREAD

**Issue by gangagyatso4364** [OpenPecha/stt-split-audio#2]
### Description
write a script to adjust the existence of shed in transcript inference in stt pecha tools. 
for given shed there should always be a space afterwards. this will reduce the annotator time significantly.
shed occurance cases:
1. inf_text                = 'ཨ་མ་ལགས་འདི་ཨ་མ་ལགས་ཀི་ལུང་པ་དེ་ག་འདྲའི་འདྲ་བོ་ཅིག་ཡོད་རེད་ཟེ། ལུང་པ། ། ལུང་པ་ལུང་ཚ་སྤོབས་པ་རེད།'
    adjusted_inf_text = 'ཨ་མ་ལགས་འདི་ཨ་མ་ལགས་ཀི་ལུང་པ་དེ་ག་འདྲའི་འདྲ་བོ་ཅིག་ཡོད་རེད་ཟེ། ལུང་པ། ལུང་པ་ལུང་ཚ་སྤོབས་པ་རེད།'
2. inf_text                = 'ཨ་མ་ལགས་འདི་ཨ་མ་ལགས་ཀི་ལུང་པ་དེ་ག་འདྲའི་འདྲ་བོ་ཅིག་ཡོད་རེད་ཟེ། ལུང་པ།།ལུང་པ་ལུང་ཚ་སྤོབས་པ་རེད།'
    adjusted_inf_text = 'ཨ་མ་ལགས་འདི་ཨ་མ་ལགས་ཀི་ལུང་པ་དེ་ག་འདྲའི་འདྲ་བོ་ཅིག་ཡོད་རེད་ཟེ། ལུང་པ། ལུང་པ་ལུང་ཚ་སྤོབས་པ་རེད།'
3. inf_text                = 'ཨ་མ་ལགས་འདི་ཨ་མ་ལགས་ཀི་ལུང་པ་དེ་ག་འདྲའི་འདྲ་བོ་ཅིག་ཡོད་རེད་ཟེ།ལུང་པ། །ལུང་པ་ལུང་ཚ་སྤོབས་པ་རེད།'
    adjusted_inf_text = 'ཨ་མ་ལགས་འདི་ཨ་མ་ལགས་ཀི་ལུང་པ་དེ་ག་འདྲའི་འདྲ་བོ་ཅིག་ཡོད་རེད་ཟེ། ལུང་པ། ལུང་པ་ལུང་ཚ་སྤོབས་པ་རེད།'
 refer clean transcription function in : [https://github.com/OpenPecha/stt-combine-datasets/blob/main/04_combine_all.ipynb](url)
### Completion Criteria
a script that is able to handle all three cases above:
### Subtasks
- [x] write a script that handles the each cases above.
- [x] look for any  other cases of shed as well.
- [x] do a test case on few of the shed misplaced cases
- [x] include in the stt-split-audio script
- [x] run the script on all the inference transcript in spilt audio when uploading new data in stt pecha tools.

**Comment by gangagyatso4364** [comment]
refer stt-combine-all for text cleaning and normalization script.

**Comment by gangagyatso4364** [comment]
update stt-split-audio with the cleaned inference text.
