### ISSUE TITLE
STT0073: LLM-Based Correction of Inference Transcriptions Using Claude AI

### ISSUE THREAD

**Issue by jim-gyas** [OpenPecha/stt-split-audio#32]
### Description:
Develop a process that improves the quality of inference transcriptions for audio files using Claude AI by aligning them with a verified transferred text. The transferred text is known for its spelling accuracy, while the inference transcription captures the audio's context more effectively. The goal is to create a corrected transcription that combines the strengths of both. The process will involve generating inference transcriptions, feeding both inference transcriptions and transferred text into Claude AI, and using its output to replace the transferred text in the original dataset.

### Resources:
1) Inference Transcription and Transferred Text : [news-catalog](https://docs.google.com/spreadsheets/d/1I5yH31BkLOls0Q0Uf_bp8tzb3kY6Q_jWdOQ4wF_2nZc/edit?gid=340421338#gid=340421338) 

### Completion Criteria:
- Claude AI processes both the inference transcriptions and transferred text to output corrected text.
- Corrected text maintains the context and meaning of the inference transcription while ensuring spelling accuracy based on the transferred text.
- A new CSV file is generated where the Transferred Text column is replaced with the Corrected Text column, retaining all other original columns.

### Subtasks:
- [ ] Generate Inference Transcription for audio files using your inference function from the stt-split-audio tool.
- [ ] Run the transfer function to obtain Transferred Text, which is considered accurate for spelling.
- [ ] Develop a prompt for Claude AI that compares the Inference Transcription with the Transferred Text.
- [ ] Focus on correcting spelling errors in the Inference Transcription while preserving the meaning and context.
- [ ] Feed both Inference Transcription and Transferred Text (matched by filename) into Claude AI. Claude outputs the Corrected Text.
- [ ] Compare the Corrected Text and Transferred Text for accuracy. If the corrected text does not match expected criteria (e.g., context, spelling), flag it for review or reprocess it using an improved Claude prompt.
- [ ] Replace the Transferred Text column with the Corrected Text, Retain all other columns from the original CSV and then Save the resulting file.

**Comment by jim-gyas** [comment]
@kaldan007 and @gangagyatso4364, could you please review my card?

**Comment by gangagyatso4364** [comment]
add the step to make cer comparison between all three kinds of  transcript generated.

**Comment by gangagyatso4364** [comment]
looks good go ahead.

**Comment by jim-gyas** [comment]
@gangagyatso4364, could you please review my updated card?

**Comment by jim-gyas** [comment]
![Image](https://github.com/user-attachments/assets/a5e35f85-18cb-4726-b581-c757b06c8107)

**Comment by jim-gyas** [comment]
```
file_name,url,inference_transcript,audio_duration,corrected_transcript,is_changed
STT_NW0802_0001_216_to_2528,https://d38pmlk0v88drf.cloudfront.net/wav16k/STT_NW0802_0001_216_to_2528.wav,ཕྱི་ལོ་ཉིས་སྟོང་ཉི་ཤུ་རྩ་བཞི་ལོའི་ཟླ་བ་བརྒྱད་པའི་ནང་།,2.312,དགའ་ལྡན་ཁྲི་ཐོག་ཁང་དང་མཁས་མང་བློ་གསལ་བྱེ་བའི་གླིང་གྲྭ་ཚང་བཅས་ནས་བརྟག་ཞུ་ཕུལ་དོན་བཞིན། བོད་མིའི་བླ་ན་མེད་པའི་དབུ་ཁྲིད་སྤྱི་ནོར་གྱི་གོང་ས་སྐྱབས་མགོན་ཆེན་པོ་མཆོག་ནས་རྒྱ་ག,True
STT_NW0802_0002_2798_to_7662,https://d38pmlk0v88drf.cloudfront.net/wav16k/STT_NW0802_0002_2798_to_7662.wav,རྒྱ་ནག་གཞུང་གིས་མཚོ་སྔོན་ཞིང་ཆེན་གོ་ལོག་ཁུལ་བཙུགས་ནས་ལོ་འཁོར་བདུན་ཅུ་འཁོ་བའི་མཛད་སྒོ་འཚོགས་ཡོད་པ་བཞིན།,4.864,"Here is the corrected transcription:

    རྒྱ་ནག་གཞུང་གིས་མཚོ་སྔོན་ཞིང་ཆེན་གོ་ལོག་ཁུལ་བཙུགས་ནས་ལོ་འཁོར་བདུན་ཅུ་འཁོ་བའི་མཛད་སྒོ་འཚོགས་ཡོད་པ་བཞིན།",True
STT_NW0802_0003_7886_to_12686,https://d38pmlk0v88drf.cloudfront.net/wav16k/STT_NW0802_0003_7886_to_12686.wav,ཕྱི་ཟླ་བརྒྱད་པའི་ནང་རྒྱ་ནག་གཞུང་གི་མགོ་ལོག་མངའ་ཁུལ་གྱི་ས་གནས་གང་སར་དམ་བསྒྲགས་ཤུགས་ཆེར་ཆེ་ཡོད་པ་དང་།,4.8,"Here is the corrected transcription:

    དགའ་ལྡན་ཁྲི་ཐོག་ཁང་དང་མཁས་མང་བློ་གསལ་བྱེ་བའི་གླིང་གྲྭ་ཚང་བཅས་ནས་བརྟག་ཞུ་ཕུལ་དོན་བཞིན། བོད་མིའི་བླ་ན་མེད་པའི་དབུ་ཁྲིད་སྤྱི་ནོར་གླིང་གྲྭ་ཚང་གི་མཁན་པོ་གསར་པའི་ཁྲི་འདོན་",True
STT_NW0802_0004_12814_to_15726,https://d38pmlk0v88drf.cloudfront.net/wav16k/STT_NW0802_0004_12814_to_15726.wav,ལྷག་པར་དགན་སྡེ་ཁག་ཏུ་ཆོས་ཕྱོགས་ཀྱི་བྱེད་སྒོ་ལ་དམ་སྒྲགས་དང་།,2.912,"Here is the transcription with spelling corrections:

    ལྷག་པར་དགན་སྡེ་ཁག་ཏུ་ཆོས་ཕྱོགས་ཀྱི་བྱེད་སྒོ་ལ་དམ་སྒྲགས་དང་། 
    དགའ་ལྡན་ཁྲི་ཐོག་ཁང་དང་མཁས་མང་བློ་གསལ་བྱེ་བའི་གླིང་གྲྭ་ཚང་བཅས་ནས་བརྟག་ཞུ་ཕུལ་དོན་བཞིན། བོད་མིའི་བླ་ན་མེད་པ",True
```

**Comment by jim-gyas** [comment]
### Transfer_text Based Correction

## No Spelling Mistake in Inference Transcript:
```
filename: STT_NW0802_0001_216_to_2528,
inference_transcript: ཕྱི་ལོ་ཉིས་སྟོང་ཉི་ཤུ་རྩ་བཞི་ལོའི་ཟླ་བ་བརྒྱད་པའི་ནང་།,
corrected_transcript: ཕྱི་ལོ་ཉིས་སྟོང་ཉི་ཤུ་རྩ་བཞི་ལོའི་ཟླ་བ་བརྒྱད་པའི་ནང་།,
is_changed: False
```

## Correction of Spelling Mistake:

```
filename: STT_NW0802_0002_2798_to_7662,
inference_transcript: རྒྱ་ནག་གཞུང་གིས་མཚོ་སྔོན་ཞིང་ཆེན་གོ་ལོག་ཁུལ་བཙུགས་ནས་ལོ་འཁོར་བདུན་ཅུ་འཁོ་བའི་མཛད་སྒོ་འཚོགས་ཡོད་པ་བཞིན།,
corrected_transcript: རྒྱ་ནག་གཞུང་གིས་མཚོ་སྔོན་ཞིང་ཆེན་མགོ་ལོག་ཁུལ་བཙུགས་ནས་ལོ་འཁོར་བདུན་ཅུ་འཁོ་བའི་མཛད་སྒོ་འཚོགས་ཡོད་པ་བཞིན།
is_changed: True
```
- Reason: 
1) Inference_transcript:
རྒྱ་ནག་གཞུང་གིས་མཚོ་སྔོན་ཞིང་ཆེན་གོ་ལོག་ཁུལ་བཙུགས་ནས་ལོ་འཁོར་བདུན་ཅུ་འཁོ་བའི་མཛད་སྒོ་འཚོགས་ཡོད་པ་བཞིན།
(This text uses གོ་ལོག་ཁུལ.)

2) corrected_transcript:
རྒྱ་ནག་གཞུང་གིས་མཚོ་སྔོན་ཞིང་ཆེན་མགོ་ལོག་ཁུལ་བཙུགས་ནས་ལོ་འཁོར་བདུན་ཅུ་འཁོ་བའི་མཛད་སྒོ་འཚོགས་ཡོད་པ་བཞིན།
(This text uses མགོ་ལོག་ཁུལ.)

- Difference:
In inference_transcript, the phrase གོ་ལོག་ཁུལ is used, whereas in corrected_transcript, it is replaced with མགོ་ལོག་ཁུལ.

**Comment by jim-gyas** [comment]
ཕྱི་ལོ་ ༢༠༢༤ ཟླ་ ༨ ནང་རྒྱ་ནག་གཞུང་གིས་མཚོ་སྔོན་ཞིང་ཆེན་མགོ་ལོག་ཁུལ་བཙུགས་ནས་ལོ་འཁོར་ ༧༠ འཁོར་བའི་མཛད་སྒོ་འཚོགས་ཡོད་པ་བཞིན། ཕྱི་ཟླ་ ༨ པའི་ནང་རྒྱ་ནག་གཞུང་གིས་མགོ་ལོག་ཁུལ་མངའ་ཁུལ་གྱི་ས་གནས་གང་སར་དམ་དྲག་ཤུགས་ཆེར་བྱས་ཡོད་པ་དང་། ལྷག་པར་དུ་དགོན་སྡེ་ཁག་ཏུ་ཆོས་ཕྱོགས་ཀྱི་བྱེད་སྒོ་ལ་དམ་དྲག་དང་བདེ་འཇགས་ཆེད་ཡིན་སྐོར་བརྗོད་ནས། དགོན་པའི་འདུ་ཁང་དང་གྲྭ་ཤག་ཁག་ཏུ་སྲིད་གཞུང་གི་ལས་བྱེད་གང་བྱུང་ཡོང་སྟེ་སྔོགས་བཤེར་དང་། ས་གནས་ཁག་ཏུ་དར་ལྕོགས་འཐེན་པ་དང་ཆོས་ལུགས་ཀྱི་མཚོན་རྟགས་རིགས་གཙང་བཟོ་བྱེད་བཞིན་པ། དགོན་པ་དང་མི་མང་གི་ཆོས་ཕྱོགས་ཀྱི་བྱེད་སྒོར་དོ་དམ་སྟངས་འཛིན་སྔར་ལྷག་བྱེད་བཞིན་ཡོད་པ། བོད་ནང་གི་འབྲེལ་ཡོད་བོད་མི་གཉིས་ནས་འདི་ག་ཨེ་ཤེ་ཡ་རང་དབང་རླུང་འཕྲིན་ཁང་ལ་འགྲེལ་བརྗོད་གནང་བྱུང་།
གོང་ཞུས་འབྲེལ་ཡོད་བོད་མི་ཞིག་ནས་ཉེ་སྔོན་མགོ་ལོག་རྨ་ཆེན་རྫོང་ཁོངས་སུ་ཡོད་པའི་རཱ་རྒྱ་གངས་ལྗོངས་ཤེས་རིག་ནོར་བུའི་གླིང་སློབ་གྲྭ་གཏོར་བཤིག་དང་འབྲེལ། རྨ་ཆེན་རྫོང་གི་མི་མང་དང་དགོན་སྡེ་ཁག་ཏུ་ཚོགས་འདུ་འདྲ་མིན་ཚོགས་ནས། རྒྱ་ནག་དམར་ཤོག་ཚོགས་པའི་ཆབ་སྲིད་སློབ་གསོ་སྤྲད་པ་དང་། དགོན་པའི་ནང་དུ་ཆབ་སྲིད་ཀྱི་ཉེན་ཁ་ཡོད་པའི་ཅ་དངོས་ཉར་ཚགས་མི་ཆོག་སྐོར་བརྗོད་ནས་འདུ་ཁང་དང་གྲྭ་ཤག་རེ་རེ་བཞིན་སྔོགས་བཤེར་དང་། དེ་བཞིན་མགོ་ལོག་པདྨ་རྫོང་སོགས་ནས་གྲོང་ཚོ་ཁག་ཏུ་ཉུལ་ཞིབ་ཀྱིས། ཡུལ་མི་ཚོའི་ཁྱིམ་ཚང་གི་སྒོ་ཁར་འཐེན་པའི་དར་ལྕོགས་དང་། ཡུལ་དེར་མི་འདས་གྲོངས་ཕྱིན་ཚེ་དར་ལྕོགས་འཐེན་སྲོལ་ཡོད་པ་སོགས་ཀྱི་ཆོས་ལུགས་ཆོ་ག་གཉེར་མི་ཆོག་པའི་དམ་དྲག་ཤུགས་ཆེར་བྱེད་བཞིན་ཡོད་སྐོར་འགྲེལ་བརྗོད་གནང་བྱུང་།
སྤྱིར་རྒྱ་ནག་གཞུང་གིས་འདི་ལོའི་ཟླ་ ༧ པའི་ནང་རྒྱ་ནག་གཞུང་གི་འབྲེལ་ཡོད་མི་སྣ་ཚོས་བོད་མདོ་སྨད་རྔ་པ་རྫོང་གི་ཡུལ་ཚོ་དང་གྲོང་སྡེ་ཁག་ཏུ་ཉུལ་ཞིབ་ཀྱིས། སྡོད་ཁང་གི་ཕྱི་ཕྱོགས་སུ་ཆོས་ལུགས་ཀྱི་མཚོན་རྟགས་ཡོད་པའི་ཅ་དངོས་རིགས་གང་ཡང་བཞག་མི་ཆོག་པའི་བཙན་ཐབས་སྣ་ཚོགས་བྱས་ཡོད་པ་རེད་ལ། ཡང་འབྲེལ་ཡོད་བོད་མི་གཞན་དེས་མགོ་ལོག་དར་ལོག་རྫོང་ཁོངས་སུ་བོད་མི་ཏང་ཡོན་ལས་བྱེད་ཚོ་ཆོས་ལུགས་བྱེད་སྒོར་ཞུགས་མི་ཆོག་པ་དང་། ལུས་ལ་ཆོས་ལུགས་ཀྱི་མཚོན་རྟགས་དང་དགོན་པ་ཁག་ཏུ་གནས་མཇལ་ལ་རྩ་ནས་འགྲོ་མི་ཆོག་པའི་དམ་དྲག་དང་། ས་གནས་ཁག་ཏུ་ཁྲིམས་ལུགས་སློབ་གསོ་ཞེས་མི་མང་བསྡུ་བསྐོངས་ཀྱིས་རྒྱ་ནག་གཅིག་གྱུར་དང་། རྒྱ་ནག་དམར་ཤོག་ཚོགས་པར་དགའ་ཞེན་དགོས་པ་དྲིལ་བསྒྲགས་བྱེད་བཞིན་ཡོད་པ་འགྲེལ་བརྗོད་གནང་གི་འདུག
རྒྱ་ནག་གཞུང་འབྲེལ་གསར་ལམ་ཁག་ཏུ་མགོ་ལོག་རྨ་ཆེན་རྫོང་དུ། འཐབ་ཕྱོགས་གཅིག་གྱུར་ལས་དོན་དང་འབྲེལ་ཡོད་ལས་བྱེད་དགོན་པ་ཁག་ཏུ་ཉུལ་ཞིབ་ཀྱིས། ཆོས་ཕྱོགས་ལས་དོན་གྱི་བདེ་འཇགས་ཉེན་ཁ་ལ་ཞིབ་ཚགས་ཀྱིས་ལྟ་ཞིབ་བྱས་ཏེ་རྫོང་ཡོངས་སུ་ཆོས་ཕྱོགས་ཀྱི་བདེ་འཇགས་ཉེན་ཁ་མི་ཡོང་བའི་འགན་ལེན་ཆེད་ཞིབ་བཤེར་དང་། མ་འོངས་པར་མུ་མཐུད་ཆོས་ལུགས་བྱེད་སྒོ་དང་དགོན་སྡེའི་དོ་དམ་ཐད་ཤུགས་སྣོན་བྱ་རྒྱུ་ཡིན་སྐོར་བཀོད་འདུག་ལ། དེ་བཞིན་གནས་ཚུལ་གཞན་ཁག་ཏུ་མགོ་ལོག་ཁུལ་འབྲིང་རིམ་མི་དམངས་ཁྲིམས་ཁང་གིས། དབྱར་ཁ་དང་བསྟུན་མི་མང་འདུ་སྡོད་ཁུལ་དུ་སྐོར་སྐྱོད་ཀྱིས་ཁྲིམས་འགལ་གྱི་གྱོད་དོན་སྐོར་གནས་ཚུལ་བསྡུ་ལེན་དང་། དམར་ཤོག་ཚོགས་པའི་དྲིལ་བསྒྲགས་སློབ་གསོ་སྤེལ་བཞིན་པའི་གནས་ཚུལ་སོགས་བཀོད་འདུག
འདས་པའི་ལོ་ཤས་ནས་བཟུང་རྒྱ་ནག་གཞུང་གིས་བོད་ནང་གི་དགོན་སྡེ་ཁག་ཏུ། ནང་བསྟན་རྒྱ་སྒྱུར་གྱི་ལས་འགུལ་འོག་དམ་དྲག་ཤུགས་ཆེར་བྱེད་བཞིན་པོ་ལྟར། འདི་ལོའི་ཕྱི་ཟླ་ ༥ པའི་ནང་དགོན་པའི་དགེ་འདུན་པར་དོ་དམ་ཤུགས་སྣོན་ཞེས། དགོན་སྡེ་ཁག་ཏུ་དྲ་ལམ་བདེ་འཇགས་ཐད་གཟབ་ནན་བྱས་ཏེ། རྒྱ་ནག་གཞུང་གི་ཆབ་སྲིད་དང་འགལ་བའི་སྐད་ཆ་མི་བཤད་པ་དང་། ཡི་གེ་མི་བསྐུར་བ། མི་རིགས་མཐུན་སྒྲིལ་གྱི་ཕྱོགས་ལ་གནོད་འཚེ་གཏོང་བའི་སྐད་ཆ་དང་ཡི་གེ་སྐུར་མི་ཆོག་པ་སོགས་ཀྱི་དམ་དྲག་དང་། དཔལ་ཡུལ་དར་ཐང་དགོན་ཆེན་གྱི་དགེ་འདུན་པ་རྒྱལ་བ་ལགས་ནས། སྤྱི་ཚོགས་དྲ་ལམ་དུ་མཆན་ཞིག་བྲིས་པ་ཆབ་སྲིད་དང་འགལ་ཡོད་སྐོར་བརྗོད་ནས་འཛིན་བཟུང་གིས་གར་སོང་ཆ་མེད་དུ་གྱུར་བ་སོགས་ཀྱི་གནས་ཚུལ་བྱུང་ཡོད་པ་རེད།
གསར་འགོད་པ། བདེ་སྐྱིད་ཀུན་སྒྲོལ།
དྲྭ་ཐོག་སྤེལ་མཁན། བདེ་སྐྱིད་ཀུན་སྒྲོལ།
